### ISSUE TITLE
这是把 Cesium 源代码在 build 的时候直接甩到发布目录下的 `/cesium/` 路径下吗？

### ISSUE THREAD

**Issue by onsummer** [nshen/vite-plugin-cesium#1]
如题

**Comment by nshen** [comment]
差不多，不拷源代码，拷贝其他依赖的东西。跟官方的  `webpack`  教程做一样的事情。

https://cesium.com/docs/tutorials/cesium-and-webpack/

> CesiumJS is a large and complex library. In additional to JavaScript modules, it also includes static assets such as CSS, image, and json files. It includes web worker files to perform intensive calculations in separate threads. Unlike traditional npm modules, CesiumJS does not define an entry point because of the diverse ways in which the library is used. We’ll need to configure some additional options to use it with webpack.

大概意思 cesium 不是一个简单的 js库，他要依赖一堆的css ，图片，json啥的。

**Comment by onsummer** [comment]
不错，我现在的项目的确配置上就是与你的思路一致的，采用的 copy 的方式，随生产而发布。
我昨晚探究了一种不需要 copy 的方式，将 `Source/` 目录下所有内容使用一款 web 服务器容器软件（例如nginx）发布为静态资源，再在入口 html 文件设定其访问路径 `CESIUM_BASE_URL` 即可，或许是一种库与用户代码分离的思路，供参考

**Comment by onsummer** [comment]
感谢贡献

**Comment by nshen** [comment]
> 不错，我现在的项目的确配置上就是与你的思路一致的，采用的 copy 的方式，随生产而发布。
> 我昨晚探究了一种不需要 copy 的方式，将 `Source/` 目录下所有内容使用一款 web 服务器容器软件（例如nginx）发布为静态资源，再在入口 html 文件设定其访问路径 `CESIUM_BASE_URL` 即可，或许是一种库与用户代码分离的思路，供参考

还是 vite 方便，自带开发服务器，保存代码还能自动刷新页面，只在第一次运行时候拷贝，之后都飞快。

> 感谢贡献

gis 新手啥都不懂，请多指教。

**Comment by LunaGod** [comment]
@nshen @onsummer 可以看看 [这个 Pull request](https://github.com/nshen/vite-plugin-cesium/pull/2) 就是直接用 `vite` 的开发服务器读取文件并返回。
