### ISSUE TITLE
怎样调试呢？

### ISSUE THREAD

**Issue by fengyun527** [nshen/vite-plugin-cesium#11]
请问通过这种构建出cesium环境后，应该怎样在浏览器的调试界面下进行调试呢？
比如在渲染过程中，怎么看cesium内部的相关变量的值（如framestate.commandList）

**Comment by nshen** [comment]
hi @fengyun527 我也不太清楚呢，webpack版本的，或者其他方式构建的可以查看到内部变量吗？

**Comment by fengyun527** [comment]
webpack我试了一下，感觉也不太行的样子，或者是没找对方法，并且这两种方式，在控制台输入viewer的时候都报 未定义 的错误
