### ISSUE TITLE
Embedded deployment not woring with an empty string as base

### ISSUE THREAD

**Issue by boardend** [nshen/vite-plugin-cesium#12]
With an empty string (`""`) as [base](https://vitejs.dev/config/#base)-option Ceisum-assets will get fetched from the root of the webserver no matter where the project was deployed. Therefore, the app will not work in a non-root directory.

With `"./"` as base everything works as excepted. So there is a workaround. But according to the Vite docs, `""` and `"./"` should both be suitable for embedded deployment.

**Comment by nshen** [comment]
HI @boardend  thanks for telling me, I haven't tried embedded deployment, but if './' works as excepted I can just set base to './' when the base is an empty string 

https://github.com/nshen/vite-plugin-cesium/commit/287538026fcf695dae8fe275a4512894cc1a48bd

I hope `v1.2.11` works for your case, thanks.
