### ISSUE TITLE
vite创建的项目使用vite-plugin-cesium，无法显示倾斜摄影模型

### ISSUE THREAD

**Issue by hanliang0112** [nshen/vite-plugin-cesium#13]
Hi，我们借助vite创建项目后使用vite-plugin-cesium，三维球都可以出现，当加载 倾斜摄影后，浏览器中无法显示。提示如下图：
![image](https://user-images.githubusercontent.com/24366464/144024687-237fed2c-5615-4a91-b512-096c1eaf0f6a.png)

**Comment by nshen** [comment]
@hanliang0112 找不到文件吧，public目录里有 `model/xxxxx 吗`

**Comment by hanliang0112** [comment]
放到public目录中还是不能显示。如下图：

![image](https://user-images.githubusercontent.com/24366464/144078536-5238c141-85ae-4f98-a6a1-d67290560a84.png)

**Comment by nshen** [comment]
我不太懂倾斜摄影，他提示找不到b3dm里边的图片，你是用什么发布的呀？

**Comment by hanliang0112** [comment]
我是直接用 cesiumlab 进行 倾斜摄影转换，转换成功会自动发布成服务提供预览。我是直接使用他们的服务。
ps： 这个服务我验证过，新创建了web项目，使用html页面显示三维，可以正常显示。但是在 vue 中就是不行  : (

**Comment by nshen** [comment]
你点击那个 `.b3dm` 的文件链接会404吗？

**Comment by hanliang0112** [comment]
点击文件链接，不会出现404，会直接下载 .b3dm 文件

![image](https://user-images.githubusercontent.com/24366464/144181702-9af3b933-d8fa-483f-b784-4a2aa4806585.png)

**Comment by nshen** [comment]
哎，奇怪呀，我加载过其他倾斜摄影当时是没有问题的。
我搜了一下
你看看是不是这个问题呀，有跨平台优化这个选项吗？
https://bbs.cesiumlab.com/question?questionId=238
