### ISSUE TITLE
构建cesium文件路径异常

### ISSUE THREAD

**Issue by jiaassh** [nshen/vite-plugin-cesium#15]
构建的时候,cesium文件夹变成了根目录,不再打包文件dist下面,这个会导致线上找不到Cesium.js

**Comment by jiaassh** [comment]
@![image](https://user-images.githubusercontent.com/30739017/145974716-9b876514-c714-46f5-981d-5b3dbef5a085.png)

**Comment by nshen** [comment]
能贴一下vite.config.js吗
