### ISSUE TITLE
构建时cesium路径错误，导致copy到dist文件夹下失败

### ISSUE THREAD

**Issue by liufch** [nshen/vite-plugin-cesium#16]
大佬，您好，我再yarn build的时候发现提示报错，查看原因发现是cesium文件夹copy到dist目录下失败，预览这块是没问题，通过代码走查，发现是由下面这段代码会引起错误
![image](https://user-images.githubusercontent.com/42931449/147307269-0b8e630f-0af1-48f9-b396-be345b6102ca.png)
如果注销掉60行代码后，就能正常打包，或者把join改成resolve也可以正常打包
由于是第一次接触vite，没有vite插件开发经验，只能先给您提出来，期待您的优化
开发环境是window

**Comment by nshen** [comment]
@liufch 谢谢提醒，可能是 vite 新版本导致，因为[有一个PR](https://github.com/nshen/vite-plugin-cesium/pull/14 )就是说这个，最近没有做这个就还没有时间试，既然你也说有问题，我就去合一下，等下发个新版本，谢谢

**Comment by nshen** [comment]
hi @liufch  试一下 v1.2.12， 是不是可以了，谢谢

**Comment by liufch** [comment]
已经可以了，谢谢@nshen

**Comment by liufch** [comment]
> hi @liufch 试一下 v1.2.12， 是不是可以了，谢谢

对，已经可以了，谢谢
