### ISSUE TITLE
增加配置项outDir和base

### ISSUE THREAD

**Issue by icedeng** [nshen/vite-plugin-cesium#18]
现在outDir和base是写死的，在做一个站点多文件夹下面的时候不方便修改。
```
function vitePluginCesium(options = {
    rebuildCesium: false,
    devMinifyCesium: false,
    outDir: 'dist',
    base: '/'
}) {
    const { rebuildCesium, devMinifyCesium, outDir } = options;
    const cesiumBuildRootPath = 'node_modules/cesium/Build';
    const cesiumBuildPath = 'node_modules/cesium/Build/Cesium/';
    let CESIUM_BASE_URL = '/cesium/';
    let base = options.base
    ....
}
```

**Comment by nshen** [comment]
感谢反馈，看了一下 outDir 是写死的，我是不是应该改成直接用 [build.outDir](https://cn.vitejs.dev/config/#build-outdir) 参数就对了？
base 应该是可以传的， ‘/' 应该只是默认值

**Comment by LunaGod** [comment]
> 我是不是应该改成直接用 build.outDir 参数

@nshen 同意沿用 vite 本身的配置，我觉得不应该添加 vite 已有的配置而增加负担，`base` 已经使用 `config.base` ，那么`outDir` 应该使用 `config.build.outDir`

**Comment by nshen** [comment]
HI @LunaGod 好久不见，等我有空改一下，还在做 cesium 相关的项目吗？
