### ISSUE TITLE
The plugin does not work in dev mode

### ISSUE THREAD

**Issue by nitenzhao** [nshen/vite-plugin-cesium#21]
The plugin works well in prod mode: compile the project with 'npm run build', and the output dist directory works with nginx.

But when in dev mode with 'npm run dev', the index page does not appear in a brower, and there is an error in browse console:
`Uncaught TypeError: Cannot read properties of undefined (reading 'Cartesian3')`

I modify the source code of the plugin in node_modules/vite-plugin-cesium/dist/index.js line:96
```
-              if (isBuild && !rebuildCesium) {
+             if (!rebuildCesium) {

```
then it works as expeted.

**Comment by nshen** [comment]
hi @nitenzhao  you should import Cartesian3 from cesium , that will be work

```js
import { Cartesian3, Viewer } from 'cesium';
let a = Cartesian3.fromArray([1, 2, 3]);
console.log(a);
```

or

```js
import * as Cesium from 'cesium';
let a = Cesium.Cartesian3.fromArray([1, 2, 3]);
console.log(a);
```

**Comment by nitenzhao** [comment]
> hi @nitenzhao you should import Cartesian3 from cesium , that will be work
> 
> ```js
> import { Cartesian3, Viewer } from 'cesium';
> let a = Cartesian3.fromArray([1, 2, 3]);
> console.log(a);
> ```
> 
> or
> 
> ```js
> import * as Cesium from 'cesium';
> let a = Cesium.Cartesian3.fromArray([1, 2, 3]);
> console.log(a);
> ```

I do import Cesium as a global object at begin:
`import * as Cesium from 'cesium';`
but later when I want to user Cesium.Cartesian3, I get the error as above

**Comment by nitenzhao** [comment]
Sorry, I make a mistake in my code, after I get rid of the mistake, the plugin works well.
