### ISSUE TITLE
dev environment won't start

### ISSUE THREAD

**Issue by ababakanian** [nshen/vite-plugin-cesium#28]
Thank you for creating this plugin, however it seems like it's not working.
current stack is

1.  vite2, 
2. react, 
3. tailwindcss, 
4. typescript, 
5. vite-plugin-cesium

running in dev mode, which is a simple "vite" call.

the server is stuck at loading and the tab needs to be closed and reopened. Attached is a sample project showing this issue
[frontend.zip](https://github.com/nshen/vite-plugin-cesium/files/8579056/frontend.zip)

perform a build and previewing the result works fine however. 
```
npm run build
npm run preview
```

My guess is there is an issue in the call
```
async closeBundle() { ... }
```

operating system ubuntu 20 LTS

**Comment by nshen** [comment]
your code works fine on my macbook pro, except it rendered two cesium instance du to <React.StrictMode> ,could you remove it and try again?

I think closeBundle function only called when build

![image](https://user-images.githubusercontent.com/181506/165681000-90474843-b334-43ec-ad81-5c37c5680973.png)

**Comment by ababakanian** [comment]
I actually tried it with https://www.npmjs.com/package/create-cesium as well and I get the same problem.
I am using Ubuntu 20 using node 16. 
Any ideas how I can debug this? I can use the source instead of the npm module and place console logs in the plugin code and will report it.
I assume there are not that many linux users here

**Comment by nshen** [comment]
I have no idea how to debug this ... I think It works on my windows WSL ubuntu18.04.

**Comment by nshen** [comment]
Do you get stuck if you don't new a Cesium View?
