### ISSUE TITLE
not found baseUrl

### ISSUE THREAD

**Issue by leimingzhang** [nshen/vite-plugin-cesium#29]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/23070813/167234055-907b4276-a9ea-4753-889f-880b38b2766a.png">

**Comment by nshen** [comment]
Are you sure this is not a cesium problem?

**Comment by andy259** [comment]
我将cesium升级到`1.94.2`，vite升级到`2.9.10`后也碰到了这个问题。开发环境下，`CESIUM_BASE_URL`的值变成了`http://localhost:3005/base/cesium/`。  

我修改下了这里，好像就可以了：
```javascript
if (!isBuild) {
      // -----------dev-----------
      userConfig.optimizeDeps = {
          exclude: ['cesium']
      };
      userConfig.define = {
          CESIUM_BASE_URL: JSON.stringify( path.posix.join(base,cesiumBuildRootPath,'CesiumUnminified'))//原来为：JSON.stringify(CESIUM_BASE_URL)
      };
  }
```

**Comment by nshen** [comment]
@andy259 我试了一下cesium 1.94.2 vite 2.9.10 ，没出现错误呢，你能不能建一个repo演示一下，或者发一下 vite.config 看看？

**Comment by andy259** [comment]
我重新安装试了下，没问题了。可能是之前版本使用的是旧版本的缓存。thanks
