### ISSUE TITLE
TypeError: cesium is not a function

### ISSUE THREAD

**Issue by ShaTao** [nshen/vite-plugin-cesium#31]

**Comment by shibingli** [comment]
"vite": "^3.0.2",
    "vite-plugin-cesium": "^1.2.19",

_` ERROR  error when starting dev server:                                                                                         
TypeError: cesium is not a function
`_

**Comment by tangerren** [comment]
not support vite3 ？

**Comment by nshen** [comment]
not test yet, breaking change?

**Comment by nshen** [comment]
这是什么原因的，我在 demo 文件夹里测试了一下，不需要 `.default` 就可以使用

**Comment by AEight1973** [comment]
我的版本是`"vite-plugin-cesium": "^1.2.19"`
我尝试自己修改了一下源码，
发现在文件 `index.js` 中将最后
`exports.default = vitePluginCesium`
修改为
`module.exports = vitePluginCesium`
就能成功运行

**Comment by amitgk1** [comment]
Opened a PR to solve this issue :)
https://github.com/nshen/vite-plugin-cesium/pull/33

**Comment by jingtian168** [comment]
> 我的版本是`"vite-plugin-cesium": "^1.2.19"`
> 我尝试自己修改了一下源码，
> 发现在文件 `index.js` 中将最后
> `exports.default = vitePluginCesium`
> 修改为
> `module.exports = vitePluginCesium`
> 就能成功运行

我刚试了 改了之后又出现其他依赖模块报错 你是怎么解决的？

**Comment by jingtian168** [comment]
> 尝试不改插件，用tiankejun的办法呢？
> [#31 (comment)](https://github.com/nshen/vite-plugin-cesium/issues/31#issuecomment-1196173048)

default 可以 但是cesium的模块 会提示不支持default 导出

**Comment by nshen** [comment]
是版本的关系吗？你按照我demo文件夹中的vite和cesium版本也会报错吗？

**Comment by nshen** [comment]
Fixed, please try  `"vite-plugin-cesium": "^1.2.20"` with ` "cesium": "1.95.0"`

@ShaTao @jingtian168  @AEight1973 @shibingli  试试刚发布的新版本。

thanks @amitgk1  for pr

```json
{
  "name": "cesium-demo",
  "version": "1.0.0",
  "license": "MIT",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite build && vite preview"
  },
  "devDependencies": {
    "cesium": "1.95.0",
    "vite": "^3.0.4",
    "vite-plugin-cesium": "^1.2.20"
  }
}
```
