### ISSUE TITLE
The requested module xxx does not provide an export named 'default' 

### ISSUE THREAD

**Issue by JSMifans** [nshen/vite-plugin-cesium#34]
mersenne-twister.js?v=f6216b95:1 Uncaught SyntaxError: The requested module '/node_modules/mersenne-twister/src/mersenne-twister.js?v=f6216b95' does not provide an export named 'default' (at mersenne-twister.js?v=f6216b95:1:10)

**Comment by nshen** [comment]
is this a bug of [mersenne-twister](https://www.npmjs.com/package/mersenne-twister) ？

**Comment by JSMifans** [comment]
> 这是[mersenne-twister](https://www.npmjs.com/package/mersenne-twister)的 bug吗？

是的把. 我把 mersenne-twister 改了 default 导出 后面就会有更多模块报错

**Comment by nshen** [comment]
跟本插件没什么关系吧。。。

**Comment by jingtian168** [comment]
> 跟本插件没什么关系吧。。。

这个问题你是怎么解决的？

**Comment by janhartmann** [comment]
I am facing the same problem with the update of Cesium to 1.96.0.

**Comment by nshen** [comment]
Seems like 1.96.0 has a big upgrade, I haven't got time to try it yet.  It's really welcome to make a PR.  

https://cesium.com/blog/2022/08/01/cesium-releases-in-august-2022/
https://cesium.com/blog/2022/07/19/build-tooling-updates-coming-to-cesiumjs/

**Comment by nshen** [comment]
hi @jingtian168  @JSMifans 由于cesium 1.96.0 改动较大，临时解决办法，固定 cesium 在 `1.95.0` 版本

Temporary solution: do not use `1.96.0`, use `1.95.0`

<img width="409" alt="image" src="https://user-images.githubusercontent.com/181506/183244016-48f8cdbb-83b5-4d84-8b46-f7d237cf5878.png">

**Comment by meschg** [comment]
Yes i can reproduce this issue in two project using https://github.com/meschg/vue-stack-cesium and also created the cesium issue above.
@nshen thanks for providing the vite plugin :)
Best wishes

**Comment by nshen** [comment]
Thanks @meschg ,  I'll keep watching that cesium issue.

your project and `worldtrix.com` look super cool.  I hope I can do some cool projects like that and play with cesium framework. But since my job now is not related to cesium, I don't have much time on that.

**Comment by nshen** [comment]
please try `vite-plugin-cesium` 1.2.21 with `cesium` 1.96.0, leave a comment if you find any problem, thanks. @JSMifans @janhartmann @jingtian168 @meschg 

```
  "devDependencies": {
    "cesium": "^1.96.0",
    "vite": "^3.0.4",
    "vite-plugin-cesium": "^1.2.21"
  }
```

**Comment by meschg** [comment]
Hi @nshen,
sorry for my late answer but I had two busy weeks at work. Thanks checking out my projects and for providing the vite-plugin. This helps me a lot!

The fix works for my projects and I confirm everything works with cesium@1.96.0 and vite-plugin-cesium@1.2.21.

I believe the only issue left  is that the npm dep was not updated to 1.96.0 from 1.95.0.
I get for further managing deb. with npm without `--force`:
```
npm ERR! While resolving: vite-plugin-cesium@1.2.21
npm ERR! Found: cesium@1.96.0
npm ERR! node_modules/cesium
npm ERR!   cesium@"^1.96.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cesium@"1.95.0" from vite-plugin-cesium@1.2.21
```
Or was this keep for a reason?
https://github.com/nshen/vite-plugin-cesium/blob/0e19e77dcb8872c7f93849320ee08453269571c5/package.json#L53 

Kind regards,
meschg

**Comment by nshen** [comment]
Hi @meschg  try 1.2.22
https://github.com/nshen/vite-plugin-cesium/blob/3fb46a510d3c90a7f2c0b9533bdb02f3b45dae4e/package.json#L53

**Comment by meschg** [comment]
Hi @nshen, 1.2.22 works perfectly. Thanks :)

**Comment by xiasun** [comment]
Any updates, gentlemen? The issue with the lack of a default export still persists in the latest version of CesiumJS. It's rather confusing.
