### ISSUE TITLE
vite 3.0 use vite-plugin-cesium Cesium is not a function

### ISSUE THREAD

**Issue by anzunyi** [nshen/vite-plugin-cesium#35]

**Comment by nshen** [comment]
#34 

Temporary solution: do not use 1.96.0, use 1.95.0

![image](https://user-images.githubusercontent.com/181506/184541011-cb735dd8-37e9-40a9-a2d5-60657e732b64.png)

**Comment by anzunyi** [comment]
> and vite-plugin-cesium 1.2.20

**Comment by anzunyi** [comment]
> Temporary solution: do not use 1.96.0, use 1.95.0，and vite-plugin-cesium 1.2.20
> 
> ```
>  "devDependencies": {
>     "cesium": "1.95.0",
>     "vite": "^3.0.4",
>     "vite-plugin-cesium": "1.2.20"
>   }
> ```
> 
> #34

As you said, I solved this problem. Thank you very much
