### ISSUE TITLE
widgets.css引入路径有误，出现Not allowed to load local resource错误

### ISSUE THREAD

**Issue by ZvonimirSun** [nshen/vite-plugin-cesium#7]
请问您遇到过这样的错误吗，cesium.js能正常引入，但是css的路径似乎有问题。

我使用yarn create cesium创建全新项目，也存在相同的问题

![image](https://user-images.githubusercontent.com/22871764/133010282-00c7181d-88ae-4225-b048-39308beb52d4.png)

和浏览器版本应该关系不大，用最新的93版本和80版本内核的chrome，没啥区别。

有些没有头绪。

**Comment by ZvonimirSun** [comment]
我使用yarn create cesium，也存在相同的问题

![image](https://user-images.githubusercontent.com/22871764/133010282-00c7181d-88ae-4225-b048-39308beb52d4.png)

测试使用的是最新的edge和chrome浏览器，93内核

**Comment by nshen** [comment]
@ZvonimirSun 感谢通知，应该是 windows 下 `path.join()` 方法会把路径组合成这种  `\\xx\\xx\\xx`，导致的加载不上来。
在 `wsl` 下应该没问题，我尝试修改一下

**Comment by ZvonimirSun** [comment]
![image](https://user-images.githubusercontent.com/22871764/133014221-e835fc07-4370-4ad8-9d50-eb5e9aecac85.png)

拼出来的路径就是这样，感觉有点问题？

我在浏览器里直接访问文件我看file协议后面跟的路径是单斜杠还是双斜杠，似乎不影响

**Comment by ZvonimirSun** [comment]
![image](https://user-images.githubusercontent.com/22871764/133015364-c8fb1f1a-156d-49de-802a-78d0ee4c62e8.png)

wsl确实没有问题。我刚刚理解错了，我想着是路径不对来着，没想着不应该是file协议访问的。

**Comment by nshen** [comment]
@ZvonimirSun  我刚修改了，更新到 1.2.9 在 windows 下应该没问题了。
`yarn add vite-plugin-cesium@1.2.9` 帮忙看一下是不是解决了，谢谢

**Comment by ZvonimirSun** [comment]
正常啦，感谢

**Comment by zairl23** [comment]
Same issue happen in mono repo using yarn workspace,
