### ISSUE TITLE
Can it run at Vuejs@3.x?

### ISSUE THREAD

**Issue by lihanqiang** [nshen/vite-plugin-cesium#8]

**Comment by nshen** [comment]
of course @lihanqiang 
you can type  `npx create-cesium`  to  create a new vue project ( [create-cesium](https://github.com/nshen/create-cesium) )
or copy code  from here https://github.com/nshen/create-cesium/tree/main/template-cesium-vue

**Comment by lihanqiang** [comment]
蟹蟹
